In [ ]:
import pandas as pd
import numpy as np
import pickle

In [83]:
df_2 = pd.read_pickle("car_data_clean_complete_v4.pkl")
df = pd.read_pickle("car_data_clean_complete_v4_le.pkl")
df_3 = pd.read_pickle("car_data_clean_complete_v5_ext.pkl")
#X = pd.read_pickle("X.pkl")
#y = pd.read_pickle("y.pkl")
#X_test = pd.read_pickle("X_test.pkl")
#X_train = pd.read_pickle("X_train.pkl")
#y_test = pd.read_pickle("y_test.pkl")
#y_train = pd.read_pickle("y_train.pkl")
gbr = pd.read_pickle("GradientBoostingRegressor_v3.pkl")
rf = pd.read_pickle("RandomForestRegressor_v2.pkl")

In [53]:
df.columns

Index(['price', 'miles', 'year', 'cylinders', 'msrp', 'is_certified',
       'engine_size', 'AGE', 'Population', 'doors', 'dom', 'dom_180',
       'dom_active', 'Median Household income num', 'make_feat', 'model_feat',
       'trim_feat', 'interior_color_feat', 'exterior_color_feat', 'zip_feat',
       'fuel_type_feat', 'States_short_feat', 'Regions_feat', 'stock_no_feat',
       'vehicle_type_feat', 'body_type_feat', 'drivetrain_feat', 'engine_feat',
       'transmission_feat'],
      dtype='object')

In [33]:
df_2.columns

Index(['id', 'vin', 'price', 'miles', 'stock_no', 'year', 'make', 'model',
       'trim', 'vehicle_type', 'body_type', 'drivetrain', 'engine',
       'engine_size', 'transmission', 'doors', 'cylinders', 'interior_color',
       'exterior_color', 'dom', 'dom_180', 'msrp', 'dom_active',
       'is_certified', 'fuel_type', 'scraped_at', 'status_date', 'AGE', 'zip',
       'type', 'decommissioned', 'primary_city', 'state', 'county', 'timezone',
       'latitude', 'longitude', 'irs_estimated_population_2015', 'county full',
       'State short', 'Per Capita income', 'Median Household income',
       'Median Family income', 'Population', 'Number of households',
       'State full', 'Regions', 'Median Household income num'],
      dtype='object')

In [84]:
X_dum = df[['make_feat', 'model_feat', 'miles', 'body_type_feat', 'year', 'zip_feat',]]
Y_dum = df.price
X_dum = pd.get_dummies(X_dum)

In [85]:
X_dum.head(100)

    make_feat  model_feat   miles  body_type_feat  year  zip_feat
0           5         559   71233               5  2012      4608
1          16         113  100215               5  2012      4608
2          15         283   44637               6  2012      4608
3           6          11   94012               6  2012      4608
4          21         118   86122               6  2012      4608
5          21          21   71624               5  2012      4608
6           2           8   73000               2  2012      4608
7           3         311   83443               6  2012      4608
8           5         141   22000               2  2012      4608
9           5         136  122336               4  2012      4608
10         13         315   84809               5  2012      4608
11          4         469   88721               5  2012      4608
12         10         132   63527               2  2012      4608
13          2           0  123602               2  2012      4608
14          9         546   75067               5  2012      4608
15         15         306  100075               6  2012      4608
16          7          70  111423               6  2012      4608
17         20         314   53200               6  2012      4608
18          5         147   99898               6  2012      4608
19         10         100   46583               5  2012      4608
20         15         280   52749               6  2012      4608
21         13         577   88536               5  2012      4608
22         21         407  131634               5  2012      4608
23         15         306   71525               6  2012      4608
24          5         541   99001               5  2012      4608
25         10         374   78477               5  2012      4608
26         10         100   82992               5  2012      4608
27         10          50   90139               6  2012      4608
28         18         345   80345               6  2012      4608
29         10          50   42155               6  2012      4608
..        ...         ...     ...             ...   ...       ...
70          8         220   80963               7  2012      4608
71          7         300   82052               5  2012      4608
72          8         198   87272               4  2012      4608
73         10         374  105583               5  2012      4608
74         10         100  121305               5  2012      4608
75          5         147  107500               6  2012      4608
76         10         374   75606               5  2012      4608
77          8         187  110369               5  2012      4608
78          7         300  109672               5  2012      4608
79         10         374   95920               5  2012      4608
80          2           8   95169               6  2012      4608
81          5         117   35867               2  2012      4608
82         13         267  101488               5  2012      4608
83         10          50   74295               6  2012      4608
84         18         572   92239               6  2012      4608
85          0         333   96374               5  2012      4608
86          3         174  124975               5  2012      4608
87          5         541   62246               5  2012      4608
88          5         508  108521               4  2012      4608
89         11         260   80679               6  2012      4608
90         13         267  118462               5  2012      4608
91         21         540   44808               4  2012      4608
92         21         118   66140               6  2012      4608
93         21         140   61141               6  2012      4608
94         18         226   82879               4  2012      4608
95         21         407   88573               5  2012      4608
96          0         333   68898               5  2012      4608
97          5         541  135137               5  2012      4608
98          9         546   62558               5  2012      4608
99         19           1   69574               4  2012      4608

[100 rows x 6 columns]

In [86]:
X_dum.shape

(1300219, 6)

In [75]:
price_pred = rf.predict(X_dum)

In [82]:
price_pred[0]

16323.7

In [90]:
print("the best price for this Subaru WRX is",rf.predict(X_dum)[0])

the best price for this Subaru WRX is 16323.7

In [87]:
price_pred = gbr.predict(X_dum)

In [88]:
price_pred[0]

16241.19897572019

In [91]:
print("the best price for this Subaru WRX is",gbr.predict(X_dum)[0])

the best price for this Subaru WRX is 16241.19897572019